### ISSUE TITLE
Is this active?

### ISSUE THREAD

**Issue by sanealytics** [googleapis/python-memcache#234]
I can't find proper documentation for it.
The last thing out there is for python 2.7!

Sure, I can figure it out using the samples, but those are auto generated and there is no index file.

The project page on pypi sends me to google which sends me to itself.

The issues and PRs seem auto generated.

Is this library actually used?

**Comment by parthea** [comment]
Hello @sanealytics,
Yes, this library is actively supported. You're correct that the samples and code is autogenerated.  Please let us know if you have specific issues or questions so we can assist further.

I've created a request for `google.cloud.memcache` sample code to be added to https://github.com/GoogleCloudPlatform/python-docs-samples
See https://github.com/GoogleCloudPlatform/python-docs-samples/issues/8804

I've also opened a bug to add an index file to the autogenerated samples directory
https://github.com/googleapis/gapic-generator-python/issues/1545

**Comment by parthea** [comment]
I'm going to close this issue but please feel free open a new issue with more information.
