### ISSUE TITLE
 bug: Tests are being installed as part of this package

### ISSUE THREAD

**Issue by msdinit** [googleapis/python-memcache#90]
Similarly to Workflows here: https://github.com/googleapis/python-workflows/issues/83 this package installs `tests` into site-packages, which can break user tests if their tests directory shares the same name.

As I am not sure how you package the release, I don't think I can contribute a PR with a fix, but please look into this.

To reproduce:

    install google-cloud-memcache
    observe tests package in your venv's site-packages

**Comment by kurtisvg** [comment]
@busunkim96 PTAL - is this a pattern we should be fixing?

**Comment by parthea** [comment]
This will be fixed in #195
